apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: web-app
  namespace: web-app
spec:
  hosts:
  - "*"
  gateways:
  - web-app-gateway
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: backend.web-app.svc.cluster.local
        port:
          number: 5000
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: frontend.web-app.svc.cluster.local
        port:
          number: 80
