apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: demo
type: kubernetes.io/dockercfg
data:
  .dockercfg: eyJnaGNyLmlvIjp7ImF1dGgiOiJkbVZ5YTJWNUJtRjBkR1Z1YjI1PSIsImVtYWlsIjoiIn19Cg==
